/* Traducción de la web en los mismos seis idiomas que el juego.
   El HTML viene escrito en español: si el visitante llega sin JavaScript,
   la página se lee igual. */

const T = {
  es: {
    navJuego: 'El juego', navSoporte: 'Soporte', navPriv: 'Privacidad',
    lema: 'Deslízate por quince planetas. Sin frenos.',
    btnStore: 'Descargar en App Store', btnVer: 'Ver capturas',
    prox: 'Próximamente en App Store',
    quéTit: 'Un descenso sin frenos',
    quéTxt: 'Bajas por la cresta de un planeta, esquivas lo que se cruza y saltas los abismos que parten el camino. Cuanto más lejos llegas, más rápido va todo.',
    c1t: 'mundos', c1p: 'Hielo, lava con volcanes, cañones de cristal, tormentas y la orilla del sol. Cruza el último portal y ganas la partida.',
    c2t: 'personajes', c2p: 'Un alienígena gris, un fantasma, un oso, un zorro, un caballero, un pulpo, un samurái, una piloto, un pingüino y más.',
    c3t: 'deslizadores', c3p: 'Del disco de repulsión a una banana que escupe fuego, un avión de hélice o un cohete de dos motores.',
    c4t: 'anuncios', c4p: 'Ni anuncios, ni cuentas, ni registro. Se juega entero sin conexión y nada de lo que haces sale de tu teléfono.',
    comoTit: 'Cómo se juega',
    como1: 'Arrastra el dedo para moverte de lado a lado.',
    como2: 'Toca la pantalla para saltar.',
    como3: 'Apoya dos dedos para impulsarte: el deslizador enciende el fuego.',
    como4: 'Pasa por las rampas: te lanzan al otro lado de los abismos.',
    capTit: 'Así se ve', tambienIpad: 'También en iPad',
    sopTit: 'Soporte',
    sopBaj: 'Cualquier duda, fallo o idea, escríbeme. Contesto en español o en inglés.',
    sopCorreo: 'Escríbeme a',
    sopResp: 'Suelo responder en un plazo de dos o tres días. Si el juego te falla, cuéntame qué iPhone o iPad tienes y qué versión de iOS: con eso lo encuentro mucho antes.',
    faqTit: 'Preguntas frecuentes',
    q1: '¿Necesito conexión a internet?',
    a1: 'No. El juego entero está dentro de la app y funciona en modo avión. Solo hace falta conexión para comprar bolsas de cristales, porque de eso se encarga la App Store.',
    q2: '¿Cómo consigo cristales y criptonitas?',
    a2: 'Los cristales se recogen jugando. Cada 50 cristales se convierten en 1 criptonita con el botón Convertir de la tienda, y con las criptonitas se compran los personajes y los deslizadores. También puedes comprar bolsas de cristales con dinero real, pero no hace falta: todo se puede desbloquear jugando.',
    q3: 'Compré una bolsa de cristales y no me llegó',
    a3: 'Cierra la app del todo y vuelve a abrirla: si el cobro se completó, los cristales entran al arrancar. Si sigue sin aparecer, escríbeme con la fecha de la compra y te ayudo.',
    q4: '¿Puedo recuperar mis compras en otro teléfono?',
    a4: 'Las bolsas de cristales son consumibles: se gastan al usarlas, así que Apple no permite restaurarlas. El progreso se guarda en el aparato, de modo que si cambias de teléfono o borras la app, empiezas de cero.',
    q5: '¿Se puede jugar sin gastar dinero?',
    a5: 'Sí. Todos los personajes y deslizadores se compran con cristales que se recogen jugando. Las bolsas solo son un atajo.',
    q6: 'Quiero que me devuelvan una compra',
    a6: 'Las devoluciones las gestiona Apple, no yo. Entra en reportaproblem.apple.com con tu Apple ID y elige la compra.',
    privTit: 'Privacidad',
    privBaj: 'Resumen: el juego no recoge ningún dato.',
    p1t: 'Qué datos recogemos', p1: 'Ninguno. Xelvora funciona por completo en tu dispositivo. No tiene cuentas, no pide registro y no envía información a ningún servidor.',
    p2t: 'Qué se guarda en tu dispositivo', p2: 'El récord de distancia, los cristales, las criptonitas, los personajes y deslizadores comprados y el idioma elegido. Todo eso vive en el almacenamiento local del juego, dentro de tu iPhone o iPad, no sale de ahí y se borra por completo si desinstalas la app.',
    p3t: 'Compras dentro de la app', p3: 'Las bolsas de cristales se cobran a través del sistema de Apple. No vemos ni guardamos tus datos de pago: los gestiona Apple con tu cuenta de App Store. El juego solo recibe la confirmación de que la compra se completó, para acreditarte los cristales.',
    p4t: 'Publicidad y seguimiento', p4: 'No hay publicidad, ni análisis de uso, ni identificadores de seguimiento. El juego no utiliza el IDFA ni ningún sistema de medición de terceros.',
    p5t: 'Menores', p5: 'El juego no recoge datos de nadie, tenga la edad que tenga.',
    p6t: 'Contacto', p6: 'Si tienes cualquier duda sobre esta política, escribe a',
    actualizado: 'Última actualización: 24 de septiembre de 2026',
    volver: 'Volver al inicio',
  },
  en: {
    navJuego: 'The game', navSoporte: 'Support', navPriv: 'Privacy',
    lema: 'Slide across fifteen planets. No brakes.',
    btnStore: 'Download on the App Store', btnVer: 'See screenshots',
    prox: 'Coming soon to the App Store',
    quéTit: 'A downhill run with no brakes',
    quéTxt: 'You ride the ridge of a planet, dodge whatever gets in the way and jump the chasms that cut the road in half. The further you get, the faster everything moves.',
    c1t: 'worlds', c1p: 'Ice, lava with erupting volcanoes, crystal canyons, storms and the edge of the sun. Cross the last portal and you win the run.',
    c2t: 'characters', c2p: 'A grey alien, a ghost, a bear, a fox, a knight, an octopus, a samurai, a pilot, a penguin and more.',
    c3t: 'sleds', c3p: 'From a repulsor disc to a fire-spitting banana, a propeller plane or a twin-engine rocket.',
    c4t: 'ads', c4p: 'No ads, no accounts, no sign-up. The whole game runs offline and nothing you do leaves your phone.',
    comoTit: 'How to play',
    como1: 'Drag your finger to move side to side.',
    como2: 'Tap the screen to jump.',
    como3: 'Hold two fingers to boost: the sled lights its fire.',
    como4: 'Hit the ramps: they launch you across the chasms.',
    capTit: 'How it looks', tambienIpad: 'Also on iPad',
    sopTit: 'Support',
    sopBaj: 'Any question, bug or idea, write to me. I answer in English or Spanish.',
    sopCorreo: 'Write to',
    sopResp: 'I usually reply within two or three days. If something breaks, tell me which iPhone or iPad you have and which iOS version: that makes it far easier to find.',
    faqTit: 'Frequently asked questions',
    q1: 'Do I need an internet connection?',
    a1: 'No. The whole game is inside the app and works in airplane mode. A connection is only needed to buy crystal packs, because the App Store handles that.',
    q2: 'How do I get crystals and kryptonite?',
    a2: 'Crystals are picked up while playing. Every 50 crystals convert into 1 kryptonite with the Convert button in the store, and kryptonite buys characters and sleds. You can also buy crystal packs with real money, but you do not need to: everything can be unlocked by playing.',
    q3: 'I bought a crystal pack and never got it',
    a3: 'Close the app completely and open it again: if the payment went through, the crystals are credited on launch. If they still do not show up, write to me with the purchase date and I will help.',
    q4: 'Can I restore my purchases on another phone?',
    a4: 'Crystal packs are consumables: they are spent when used, so Apple does not allow restoring them. Progress is stored on the device, so if you switch phones or delete the app you start over.',
    q5: 'Can I play without spending money?',
    a5: 'Yes. Every character and sled is bought with crystals picked up while playing. The packs are only a shortcut.',
    q6: 'I want a refund',
    a6: 'Refunds are handled by Apple, not by me. Go to reportaproblem.apple.com with your Apple ID and pick the purchase.',
    privTit: 'Privacy',
    privBaj: 'Short version: the game collects no data at all.',
    p1t: 'What data we collect', p1: 'None. Xelvora runs entirely on your device. It has no accounts, asks for no sign-up and sends no information to any server.',
    p2t: 'What is stored on your device', p2: 'Your best distance, crystals, kryptonite, purchased characters and sleds, and the chosen language. All of it lives in the game’s local storage on your iPhone or iPad, never leaves it, and is deleted completely if you uninstall the app.',
    p3t: 'In-app purchases', p3: 'Crystal packs are charged through Apple’s system. We never see or store your payment details: Apple handles them with your App Store account. The game only receives the confirmation that the purchase went through, so it can credit your crystals.',
    p4t: 'Advertising and tracking', p4: 'There is no advertising, no usage analytics and no tracking identifiers. The game does not use the IDFA or any third-party measurement system.',
    p5t: 'Children', p5: 'The game collects no data from anyone, at any age.',
    p6t: 'Contact', p6: 'Questions about this policy:',
    actualizado: 'Last updated: 24 September 2026',
    volver: 'Back to the home page',
  },
  fr: {
    navJuego: 'Le jeu', navSoporte: 'Assistance', navPriv: 'Confidentialité',
    lema: 'Glissez sur quinze planètes. Sans freins.',
    btnStore: 'Télécharger sur l’App Store', btnVer: 'Voir les captures',
    prox: 'Bientôt sur l’App Store',
    quéTit: 'Une descente sans freins',
    quéTxt: 'Vous dévalez la crête d’une planète, évitez ce qui se présente et sautez les gouffres qui coupent la route. Plus vous avancez, plus tout va vite.',
    c1t: 'mondes', c1p: 'Glace, lave et volcans en éruption, canyons de cristal, orages et le bord du soleil. Franchissez le dernier portail et la partie est gagnée.',
    c2t: 'personnages', c2p: 'Un alien gris, un fantôme, un ours, un fennec, un chevalier, une pieuvre, un samouraï, une pilote, un manchot et d’autres.',
    c3t: 'planches', c3p: 'Du disque à répulsion à une banane qui crache du feu, un avion à hélice ou une fusée à deux moteurs.',
    c4t: 'publicités', c4p: 'Pas de publicité, pas de compte, pas d’inscription. Tout le jeu fonctionne hors ligne et rien ne quitte votre téléphone.',
    comoTit: 'Comment jouer',
    como1: 'Faites glisser le doigt pour vous déplacer.',
    como2: 'Touchez l’écran pour sauter.',
    como3: 'Posez deux doigts pour accélérer : la planche s’enflamme.',
    como4: 'Prenez les rampes : elles vous propulsent par-dessus les gouffres.',
    capTit: 'En images', tambienIpad: 'Aussi sur iPad',
    sopTit: 'Assistance',
    sopBaj: 'Une question, un bug ou une idée : écrivez-moi. Je réponds en anglais ou en espagnol.',
    sopCorreo: 'Écrivez à',
    sopResp: 'Je réponds en général sous deux ou trois jours. En cas de problème, indiquez votre modèle d’iPhone ou d’iPad et votre version d’iOS.',
    faqTit: 'Questions fréquentes',
    q1: 'Faut-il une connexion internet ?',
    a1: 'Non. Tout le jeu est dans l’app et fonctionne en mode avion. La connexion ne sert qu’à acheter des sacs de cristaux, géré par l’App Store.',
    q2: 'Comment obtenir des cristaux et de la kryptonite ?',
    a2: 'Les cristaux se ramassent en jouant. 50 cristaux donnent 1 kryptonite avec le bouton Convertir, et la kryptonite achète les personnages et les planches. Tout peut se débloquer sans payer.',
    q3: 'J’ai acheté un sac de cristaux et je ne l’ai pas reçu',
    a3: 'Fermez complètement l’app et rouvrez-la : si le paiement a abouti, les cristaux arrivent au démarrage. Sinon, écrivez-moi avec la date de l’achat.',
    q4: 'Puis-je restaurer mes achats sur un autre téléphone ?',
    a4: 'Les sacs de cristaux sont des consommables : Apple ne permet pas de les restaurer. La progression reste sur l’appareil.',
    q5: 'Peut-on jouer sans dépenser d’argent ?',
    a5: 'Oui. Tous les personnages et planches s’achètent avec les cristaux ramassés en jouant.',
    q6: 'Je veux un remboursement',
    a6: 'Les remboursements sont gérés par Apple : reportaproblem.apple.com avec votre identifiant Apple.',
    privTit: 'Confidentialité',
    privBaj: 'En résumé : le jeu ne collecte aucune donnée.',
    p1t: 'Données collectées', p1: 'Aucune. Xelvora fonctionne entièrement sur votre appareil, sans compte ni inscription, et n’envoie rien à aucun serveur.',
    p2t: 'Ce qui est enregistré sur l’appareil', p2: 'Votre record, les cristaux, la kryptonite, les personnages et planches achetés et la langue choisie. Tout cela reste dans le stockage local du jeu et disparaît si vous désinstallez l’app.',
    p3t: 'Achats intégrés', p3: 'Les sacs de cristaux sont facturés par le système d’Apple. Nous ne voyons jamais vos données de paiement ; le jeu reçoit seulement la confirmation de l’achat.',
    p4t: 'Publicité et suivi', p4: 'Aucune publicité, aucune analyse d’usage, aucun identifiant de suivi. Le jeu n’utilise pas l’IDFA.',
    p5t: 'Mineurs', p5: 'Le jeu ne collecte les données de personne, quel que soit son âge.',
    p6t: 'Contact', p6: 'Pour toute question sur cette politique :',
    actualizado: 'Dernière mise à jour : 24 septembre 2026',
    volver: 'Retour à l’accueil',
  },
  it: {
    navJuego: 'Il gioco', navSoporte: 'Assistenza', navPriv: 'Privacy',
    lema: 'Scivola su quindici pianeti. Senza freni.',
    btnStore: 'Scarica su App Store', btnVer: 'Guarda le immagini',
    prox: 'Presto su App Store',
    quéTit: 'Una discesa senza freni',
    quéTxt: 'Scendi lungo la cresta di un pianeta, schivi quello che ti capita davanti e salti gli abissi che tagliano la strada. Più vai lontano, più tutto accelera.',
    c1t: 'mondi', c1p: 'Ghiaccio, lava con vulcani in eruzione, canyon di cristallo, tempeste e il bordo del sole. Attraversa l’ultimo portale e hai vinto.',
    c2t: 'personaggi', c2p: 'Un alieno grigio, un fantasma, un orso, una volpe, un cavaliere, un polpo, un samurai, una pilota, un pinguino e altri.',
    c3t: 'tavole', c3p: 'Dal disco a repulsione a una banana che sputa fuoco, un aereo a elica o un razzo a due motori.',
    c4t: 'pubblicità', c4p: 'Niente pubblicità, niente account, niente registrazione. Tutto offline e niente esce dal telefono.',
    comoTit: 'Come si gioca',
    como1: 'Trascina il dito per spostarti.',
    como2: 'Tocca lo schermo per saltare.',
    como3: 'Appoggia due dita per la spinta: la tavola accende il fuoco.',
    como4: 'Prendi le rampe: ti lanciano oltre gli abissi.',
    capTit: 'Come si vede', tambienIpad: 'Anche su iPad',
    sopTit: 'Assistenza',
    sopBaj: 'Per domande, problemi o idee, scrivimi. Rispondo in inglese o in spagnolo.',
    sopCorreo: 'Scrivi a',
    sopResp: 'Di solito rispondo in due o tre giorni. Se qualcosa non va, dimmi che iPhone o iPad hai e quale versione di iOS.',
    faqTit: 'Domande frequenti',
    q1: 'Serve la connessione a internet?',
    a1: 'No. Tutto il gioco è dentro l’app e funziona in modalità aereo. Serve solo per comprare i sacchetti di cristalli.',
    q2: 'Come ottengo cristalli e kryptonite?',
    a2: 'I cristalli si raccolgono giocando. Ogni 50 cristalli diventano 1 kryptonite con il pulsante Converti, e con la kryptonite si comprano personaggi e tavole. Si può sbloccare tutto senza pagare.',
    q3: 'Ho comprato un sacchetto e non è arrivato',
    a3: 'Chiudi del tutto l’app e riaprila: se il pagamento è andato a buon fine, i cristalli arrivano all’avvio. Altrimenti scrivimi con la data dell’acquisto.',
    q4: 'Posso ripristinare gli acquisti su un altro telefono?',
    a4: 'I sacchetti sono consumabili: Apple non ne permette il ripristino. I progressi restano sul dispositivo.',
    q5: 'Si può giocare senza spendere?',
    a5: 'Sì. Tutti i personaggi e le tavole si comprano con i cristalli raccolti giocando.',
    q6: 'Voglio un rimborso',
    a6: 'I rimborsi li gestisce Apple: reportaproblem.apple.com con il tuo ID Apple.',
    privTit: 'Privacy',
    privBaj: 'In breve: il gioco non raccoglie alcun dato.',
    p1t: 'Quali dati raccogliamo', p1: 'Nessuno. Xelvora funziona interamente sul dispositivo, senza account né registrazione, e non invia nulla a nessun server.',
    p2t: 'Cosa si salva sul dispositivo', p2: 'Record di distanza, cristalli, kryptonite, personaggi e tavole acquistati e lingua scelta. Resta tutto nella memoria locale del gioco e sparisce se disinstalli l’app.',
    p3t: 'Acquisti in-app', p3: 'I sacchetti di cristalli vengono addebitati dal sistema di Apple. Non vediamo né conserviamo i tuoi dati di pagamento; il gioco riceve solo la conferma dell’acquisto.',
    p4t: 'Pubblicità e tracciamento', p4: 'Nessuna pubblicità, nessuna analisi d’uso, nessun identificatore di tracciamento. Il gioco non usa l’IDFA.',
    p5t: 'Minori', p5: 'Il gioco non raccoglie dati da nessuno, a qualsiasi età.',
    p6t: 'Contatti', p6: 'Per domande su questa informativa:',
    actualizado: 'Ultimo aggiornamento: 24 settembre 2026',
    volver: 'Torna alla home',
  },
  ja: {
    navJuego: 'ゲーム', navSoporte: 'サポート', navPriv: 'プライバシー',
    lema: '15の惑星を滑り抜けろ。ブレーキはない。',
    btnStore: 'App Storeでダウンロード', btnVer: 'スクリーンショット',
    prox: 'App Storeで近日公開',
    quéTit: 'ブレーキのない滑降',
    quéTxt: '惑星の尾根を滑り降り、行く手をはばむ岩をよけ、道を断つ谷を飛び越えます。進むほど、すべてが速くなります。',
    c1t: 'の世界', c1p: '氷、火山が噴火する溶岩、クリスタルの峡谷、嵐、そして太陽のふち。最後のポータルを抜ければ勝利です。',
    c2t: '人のキャラ', c2p: 'グレイのエイリアン、幽霊、ヒグマ、フェネック、騎士、タコ、侍、パイロット、ペンギンなど。',
    c3t: 'つのボード', c3p: '反発ディスクから火を噴くバナナ、プロペラ機、双発ロケットまで。',
    c4t: '広告ゼロ', c4p: '広告もアカウントも登録もありません。すべてオフラインで動き、データは端末の外に出ません。',
    comoTit: '遊びかた',
    como1: '指をスライドさせて左右に移動。',
    como2: '画面をタップしてジャンプ。',
    como3: '2本指で押さえるとブースト。ボードに火がつきます。',
    como4: 'ランプに乗れば、谷の向こうまで飛べます。',
    capTit: '画面', tambienIpad: 'iPadにも対応',
    sopTit: 'サポート',
    sopBaj: 'ご質問、不具合、ご意見はメールでお寄せください。英語かスペイン語で返信します。',
    sopCorreo: '連絡先',
    sopResp: '通常2〜3日以内に返信します。不具合の場合は、お使いのiPhoneまたはiPadの機種とiOSのバージョンをお知らせください。',
    faqTit: 'よくある質問',
    q1: 'インターネット接続は必要ですか？',
    a1: 'いいえ。ゲームはすべてアプリ内にあり、機内モードでも遊べます。接続が必要なのはクリスタルの購入時だけです。',
    q2: 'クリスタルとクリプトナイトの入手方法は？',
    a2: 'クリスタルはプレイ中に集まります。ストアの「変換」ボタンで50クリスタルが1クリプトナイトになり、キャラクターとボードを購入できます。課金しなくてもすべて解放できます。',
    q3: 'クリスタルを購入したのに反映されません',
    a3: 'アプリを完全に終了して開き直してください。決済が完了していれば起動時に反映されます。それでも反映されない場合は購入日を添えてご連絡ください。',
    q4: '別の端末で購入を復元できますか？',
    a4: 'クリスタルは消耗型のため、Appleの仕様で復元できません。進行状況は端末内に保存されます。',
    q5: '無料で遊べますか？',
    a5: 'はい。すべてのキャラクターとボードは、プレイ中に集めたクリスタルで購入できます。',
    q6: '返金してほしい',
    a6: '返金はAppleが対応します。reportaproblem.apple.com にApple IDでアクセスしてください。',
    privTit: 'プライバシー',
    privBaj: '要点：このゲームはデータを一切収集しません。',
    p1t: '収集するデータ', p1: 'ありません。Xelvoraは完全に端末内で動作し、アカウントも登録もなく、サーバーへ情報を送信しません。',
    p2t: '端末に保存されるもの', p2: '最高距離、クリスタル、クリプトナイト、購入したキャラクターとボード、選択した言語。すべてゲームのローカル保存領域にあり、アプリを削除すると消えます。',
    p3t: 'アプリ内課金', p3: 'クリスタルの購入はAppleの仕組みで処理されます。支払い情報を当方が見ることはありません。ゲームは購入完了の通知だけを受け取ります。',
    p4t: '広告とトラッキング', p4: '広告、利用解析、トラッキング識別子はありません。IDFAも使用しません。',
    p5t: 'お子様について', p5: '年齢を問わず、誰のデータも収集しません。',
    p6t: 'お問い合わせ', p6: 'このポリシーに関するお問い合わせ：',
    actualizado: '最終更新：2026年9月24日',
    volver: 'ホームに戻る',
  },
  zh: {
    navJuego: '游戏', navSoporte: '支持', navPriv: '隐私',
    lema: '滑越十五颗星球。没有刹车。',
    btnStore: '在 App Store 下载', btnVer: '查看截图',
    prox: '即将登陆 App Store',
    quéTit: '一场没有刹车的滑行',
    quéTxt: '沿着星球的山脊向下滑行，躲开挡路的岩石，飞跃切断道路的深渊。滑得越远，一切就越快。',
    c1t: '个星球', c1p: '冰原、火山喷发的熔岩、水晶峡谷、风暴，还有太阳的边缘。穿过最后一道传送门就算通关。',
    c2t: '个角色', c2p: '灰色外星人、幽灵、棕熊、狐狸、骑士、章鱼、武士、飞行员、企鹅等。',
    c3t: '款滑板', c3p: '从斥力圆盘到喷火的香蕉、螺旋桨飞机，或者双引擎火箭。',
    c4t: '零广告', c4p: '没有广告、没有账号、无需注册。全程离线，数据不离开你的手机。',
    comoTit: '玩法',
    como1: '滑动手指左右移动。',
    como2: '点击屏幕跳跃。',
    como3: '双指按住加速，滑板会喷出火焰。',
    como4: '冲上跳台，飞过深渊。',
    capTit: '游戏画面', tambienIpad: '也支持 iPad',
    sopTit: '支持',
    sopBaj: '有任何问题、故障或建议，欢迎来信。我会用英文或西班牙文回复。',
    sopCorreo: '联系邮箱',
    sopResp: '通常两三天内回复。如果遇到故障，请告诉我你的 iPhone 或 iPad 型号和 iOS 版本。',
    faqTit: '常见问题',
    q1: '需要联网吗？',
    a1: '不需要。整个游戏都在应用内，飞行模式也能玩。只有购买水晶时需要联网，那由 App Store 处理。',
    q2: '怎么获得水晶和氪石？',
    a2: '水晶在游戏中收集。在商店点「兑换」，每 50 水晶换 1 氪石，用氪石购买角色和滑板。不花钱也能解锁全部内容。',
    q3: '我买了水晶但没有到账',
    a3: '请完全关闭应用后重新打开：如果付款成功，水晶会在启动时到账。若仍未到账，请把购买日期发给我。',
    q4: '可以在另一台手机上恢复购买吗？',
    a4: '水晶属于消耗型项目，Apple 不支持恢复。游戏进度保存在设备上。',
    q5: '不花钱能玩吗？',
    a5: '可以。所有角色和滑板都能用游戏中收集的水晶购买。',
    q6: '我想退款',
    a6: '退款由 Apple 处理：用 Apple ID 登录 reportaproblem.apple.com。',
    privTit: '隐私',
    privBaj: '简单说：本游戏不收集任何数据。',
    p1t: '我们收集哪些数据', p1: '没有。Xelvora 完全在你的设备上运行，没有账号、无需注册，也不会向任何服务器发送信息。',
    p2t: '设备上保存了什么', p2: '最远距离、水晶、氪石、已购买的角色和滑板，以及所选语言。全部保存在游戏的本地存储中，卸载应用即全部删除。',
    p3t: '应用内购买', p3: '水晶通过 Apple 的系统收费。我们看不到也不会保存你的支付信息，游戏只会收到购买成功的确认。',
    p4t: '广告与追踪', p4: '没有广告、没有使用分析、没有追踪标识符。游戏不使用 IDFA。',
    p5t: '未成年人', p5: '本游戏不收集任何人的数据，无论年龄。',
    p6t: '联系方式', p6: '关于本政策的疑问：',
    actualizado: '最后更新：2026年9月24日',
    volver: '返回首页',
  },
};

const CLAVE = 'xelvora_web_lang';

function detectar() {
  try {
    const guardado = localStorage.getItem(CLAVE);
    if (guardado && T[guardado]) return guardado;
  } catch (e) { /* sin almacenamiento: seguimos con el idioma del navegador */ }
  for (const l of (navigator.languages || [navigator.language || 'es'])) {
    const c = String(l).slice(0, 2).toLowerCase();
    if (T[c]) return c;
  }
  return 'es';
}

function aplicar(lang) {
  const dic = T[lang] || T.es;
  document.documentElement.lang = lang === 'zh' ? 'zh-Hans' : lang;
  document.querySelectorAll('[data-t]').forEach((el) => {
    const v = dic[el.dataset.t];
    if (v !== undefined) el.textContent = v;
  });
  try { localStorage.setItem(CLAVE, lang); } catch (e) { /* nada que hacer */ }
  const sel = document.getElementById('selIdioma');
  if (sel) sel.value = lang;
}

document.addEventListener('DOMContentLoaded', () => {
  aplicar(detectar());
  const sel = document.getElementById('selIdioma');
  if (sel) sel.addEventListener('change', () => aplicar(sel.value));
});
